# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 17:28
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_model_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='category')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
                'db_table': 'category',
                'ordering': ('tree_id', 'level'),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True)),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='blog.Genre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50, unique=True, verbose_name='Search')),
            ],
            options={
                'verbose_name': 'keywords',
                'db_table': 'keywords',
                'verbose_name_plural': 'keywords',
            },
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.TextField(verbose_name='address contact')),
                ('opisanie', models.TextField(verbose_name='opisanie')),
                ('site_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='images')),
                ('about_me', models.TextField(verbose_name='about me')),
                ('about_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='about content')),
                ('about_opisanie', models.TextField(verbose_name='about discription')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='images')),
                ('contact_me', models.TextField(verbose_name='contact me')),
                ('contact_content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='contact content')),
                ('contact_opisanie', models.TextField(verbose_name='contact opisanie')),
                ('contact_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='images site')),
            ],
            options={
                'db_table': 'site',
            },
        ),
        migrations.CreateModel(
            name='Vkladki',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField(verbose_name='text field')),
                ('nazvanie', models.TextField(verbose_name='name')),
            ],
            options={
                'db_table': 'vkladki',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='header'),
        ),
    ]
