# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 17:40
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170611_1728'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='discription',
        ),
        migrations.AddField(
            model_name='post',
            name='article_taxt',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, verbose_name='preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='article_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, verbose_name='preview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='blog.Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(related_name='keywords', related_query_name='keyword', to='blog.Keywords', verbose_name='tags'),
        ),
    ]
