# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 18:10
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170611_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='article_taxt',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='article_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
