# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-11 18:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170611_1827'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
