# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 15:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_delete_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='article_taxt',
        ),
        migrations.RemoveField(
            model_name='post',
            name='article_text',
        ),
        migrations.AddField(
            model_name='post',
            name='image_eight',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_five',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_four',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_one',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_seven',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_six',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_three',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_two',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_five',
            field=models.TextField(default=datetime.datetime(2017, 6, 9, 15, 2, 42, 979017, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_four',
            field=models.TextField(default=datetime.datetime(2017, 6, 9, 15, 2, 59, 886721, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_one',
            field=models.TextField(default=datetime.datetime(2017, 6, 9, 15, 3, 28, 602454, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_three',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_two',
            field=models.TextField(default=datetime.datetime(2017, 6, 9, 15, 3, 50, 863145, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='model_pic',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AlterModelTable(
            name='post',
            table=None,
        ),
    ]
