# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-09 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20170609_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='aline_three',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='post',
            name='aline_two',
            field=models.BooleanField(default=True),
        ),
    ]
