# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-12 15:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170609_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_nine',
            field=models.ImageField(default='pic_folder/None/no-img.jpg', upload_to='pic_folder/', verbose_name='blogpic'),
        ),
        migrations.AddField(
            model_name='post',
            name='text_seven',
            field=models.TextField(default=datetime.datetime(2017, 6, 12, 15, 57, 15, 126022, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='text_six',
            field=models.TextField(default=datetime.datetime(2017, 6, 12, 15, 57, 26, 61381, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
