# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 15:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170612_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2017, 6, 18, 15, 50, 40, 697139, tzinfo=utc), unique=True),
            preserve_default=False,
        ),
    ]
