# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20170618_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='aline_three',
            field=models.BooleanField(default=False),
        ),
    ]
