# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-18 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20170618_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='aline_vid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='aline_three',
            field=models.BooleanField(default=True),
        ),
    ]
