# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 19:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_blog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
